### ISSUE TITLE
使用时报错

### ISSUE THREAD

**Issue by JeremyHe-cn** [mawenbao/pelican-update-date#2]
添加此插件后，进行make html报以下错误
```
CRITICAL: 'Static' object has no attribute 'date'
```

文章的matedate为
```
Title: test
Date: 2014-07-24 10:07
Update: 2014-07-24 18:07
```

**Comment by mawenbao** [comment]
你的pelican是哪个版本的？`pelican --version`，我的pelican 3.5.0没什么问题，方便的话可以升级一下。

**Comment by JeremyHe-cn** [comment]
最新的，前两天刚装的。使用的是VirtualEnv+pelicann+python2.7  

看了下，官方用的字段是Modified，顺便问下为什么这个插件独立使用Update这个新增字段呢

**Comment by mawenbao** [comment]
早期的pelican不支持修改时间，所以才自己搞了个插件。

**Comment by JeremyHe-cn** [comment]
经过调试，发现是执行以下内容的时候会报错
```
if content.date.tzinfo is not None:
        content.updatedate = set_date_tzinfo(content.updatedate, content.date.tzinfo.zone)
```
报错内容为：
```
CRITICAL: 'Static' object has no attribute 'date'
```

另外，插件中，register函数有两个。python不太了解，但是从其他语言的基础上来说，这不是函数重载吧？这里是不是有问题呢？

ps: 现在我已经放弃使用这个插件了，因为我要的效果只是在文章右侧显示修改时间而已，所以自己修改了主题，用modified代替update，如果需要，我可以提个pull request^_^

**Comment by mawenbao** [comment]
1. register函数确实是写重复了，多谢你提醒，已经改掉了。
2. 如果只是需要显示修改时间，建议直接用pelican自带的修改时间功能。那个问题我猜可能是你测试的markdown文件里没有定义Date吧。

这个issue我先关掉了。

**Comment by alvminvm** [comment]
看我最初提这个问题的内容。是有定义Date。
并且我试过用大小写
Date和date
所以如果要找出这个问题的原因并解决，你可能得花点时间查一下

**Comment by mawenbao** [comment]
你好，我花时间查了一下，确实是因为markdown文件没有定义date（大小写无所谓）引起的。

peican里有一个设置`DEFAULT_DATE = 'fs'`，意思是如果没有定义date属性，那么pelican会使用文件的修改时间作为date的值，我猜你可能有某个markdown文件没有定义date，而且没有配置`DEFAULT_DATE`。

不过最近的提交里我已经对是否有date属性进行了判断，不判断确实是有问题的。
